In [6]:
import pandas as pd 
import numpy as np

In [50]:
u = np.array([1,3,4,1])
v = np.array([3,4,0,1])
u.shape[0]
v.shape[0]

4

In [22]:
def u_v_mult(u,v) : 
 u.shape[0]==v.shape[0]
 n = u.shape[0]
 result =0
 for i in range(n) : 
        result = result+ u[i]*v[i]
 return result  
    

In [51]:
print(u_v_mult(u,v))

16


In [67]:
U = np.array([[1,3,4,2],[2,4,5,4],[2,6,8,7],[1,2,3,4]])
V = np.array([[1,3,4,2],[2,4,3,4],[2,3,8,7],[1,35,5,5]])

In [32]:
U.shape[1]

3

In [47]:
def U_v_mult(U,v) : 
 assert U.shape[1]==v.shape[0]
 rows = U.shape[0]
 result = np.zeros(rows)
 for i in range(rows):
        result[i] = u_v_mult(U[i],v)
 return result

In [48]:
U_v_mult(U,v)

array([16., 26., 37.])

In [68]:
def U_V_Multp(U,V):
 U.shape[1]==V.shape[0]
 rows = U.shape[1]
 cols = V.shape[0]
 result = np.zeros((rows,cols))
 for i in range(rows):
    for j in range(cols):
        result[i][j] = u_v_mult(U[i,:],V[:,j])
 return result

In [69]:
U_V_Multp(U,V)

array([[ 17.,  97.,  55.,  52.],
       [ 24., 177.,  80.,  75.],
       [ 37., 299., 125., 119.],
       [ 15., 160.,  54.,  51.]])

In [70]:
U.dot(V)

array([[ 17,  97,  55,  52],
       [ 24, 177,  80,  75],
       [ 37, 299, 125, 119],
       [ 15, 160,  54,  51]])

In [2]:
import numpy as np

In [5]:
weight = np.array([80,79,78,77,76,75])
height = np.array([1.62,1.5,1.7,1.4,1.8,1.59])
bmi = weight/(height*height)
print(bmi)

[30.48315806 35.11111111 26.98961938 39.28571429 23.45679012 29.666548  ]


In [6]:
bmi >25

array([ True,  True,  True,  True, False,  True])

In [8]:
bmi[bmi>25]

array([30.48315806, 35.11111111, 26.98961938, 39.28571429, 29.666548  ])

In [4]:
import pandas as pd 
pd.__version__


'2.2.2'

In [6]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-09-30 17:55:56--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: 'laptops.csv'

laptops.csv         100%[===================>] 291.58K  --.-KB/s    in 0.1s    

2024-09-30 17:55:57 (2.45 MB/s) - 'laptops.csv' saved [298573/298573]



In [10]:
df = pd.read_csv('laptops.csv')
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [22]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [35]:
df[df['Brand']=='Dell']['Final Price'].max()

3936.0

In [38]:
df[['Screen']].median()

Screen    15.6
dtype: float64

In [61]:
x=df[['Screen']].mode()

In [62]:
df[['Screen']].fillna(x)


Screen
0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
...      ...
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4

[2160 rows x 1 columns]

In [63]:
df[['Screen']].fillna(x).mean()

Screen    15.168112
dtype: float64

In [70]:
import numpy as np
x=np.array(df[df['Brand']=='Innjoo'][['RAM','Storage','Screen']])
x

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [77]:
xt= np.transpose(x)
xtx= xt.dot(x)
xtx.shape

(3, 3)

In [82]:
xt.shape

(3, 6)

In [80]:
z=np.linalg.inv(xtx)
z.shape

(3, 3)

In [88]:
qq= z.dot(xt)
qq.shape

(3, 6)

In [86]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y.shape

(6,)

In [90]:
w=qq.dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [91]:
w.sum()

91.2998806299555